#######analyze data generated by 10x genomics platform

library(hypeR)
library(doParallel)
library(org.Hs.eg.db)
library(pCalibrate)
library(ggplot2)
library(Seurat)
library(RColorBrewer)
library(wordcloud)

#####function to generate a useful data.frame from a seurat object
probs<-function(object) {
  require(foreach)
  require(Seurat)
  clusters<-object@meta.data$seurat_clusters
  rawdata<-object@assays$RNA@counts
  cluster.probs<-foreach(i=0:max(as.numeric(levels(clusters))),.combine='cbind') %dopar% {
    clust.mat<-rawdata[,clusters==i]
    apply(clust.mat,1,function(x) length(which(x>0))/length(x))
  }
  
  delta.probs<-foreach(i=1:dim(cluster.probs)[2],.combine='cbind') %do% {
    fin<-foreach(m=1:dim(cluster.probs)[2],.combine='cbind') %dopar% {
      cluster.probs[,i]-cluster.probs[,m]
    }
    fin<-apply(fin,1,sum)
    return(fin)
  }
  c.names<-paste("Cluster",as.numeric(levels(clusters)),sep="_")
  colnames(delta.probs)<-c.names
  colnames(cluster.probs)<-c.names
  fin<-list(cluster.probs,delta.probs)
  return(fin)
}


######load count data after processing and create a Seurat object
load("~/Desktop/R/10x/BOL14172_dge_raw.Rdata")
RPE10x <- CreateSeuratObject(counts = dge, project = "RPE10x", min.cells = 3, min.features = 200)

RPE10x <- PercentageFeatureSet(RPE10x, pattern = "^MT-", col.name = "percent.mt")
# run sctransform
RPE10x <- SCTransform(RPE10x, vars.to.regress = "percent.mt", verbose = FALSE)
RPE10x <- FindVariableFeatures(RPE10x, selection.method = "vst", nfeatures = 2000)
RPE10x <- RunPCA(RPE10x, features = VariableFeatures(RPE10x), verbose = FALSE)
RPE10x <- RunUMAP(RPE10x, dims = 1:50, verbose = FALSE)
RPE10x <- FindNeighbors(RPE10x, dims = 1:50, verbose = FALSE)
RPE10x <- FindClusters(RPE10x, resolution = 1, verbose = FALSE)
RPE10x@meta.data$patient<-"4"
markers.10x<-FindAllMarkers(RPE10x, min.pct = 0.25)

#### analyze and generate figure panels

obj<-RNA.10x
DimPlot(obj)
DotPlot(obj,features=rev(c("RPE65","BEST1","BMP4","VSX1","VSX2","RHO","SAG","PDE6A")),scale.min = 0)

####read in RPE signiture list from PMID:26517551
x<-read.csv("human_RPE_signature_genes_26517551.csv",as.is=T)
y<-intersect(rownames(obj@assays$SCT@scale.data),x[,1])
z<-setdiff(x[,1],y)
z<-heatmap(obj@assays$SCT@scale.data[y,])
DoHeatmap(obj,features=rev(y[z$rowInd]))+scale_fill_distiller(palette="RdYlBu")

####make an upset plot of interwsection between 10X cluster exression and the RPE signature genes
test<-probs(obj)
m<-test[[1]][which((apply(test[[1]][intersect(rownames(test[[1]]),x[,1]),7:8],1,max)>0)),]
m<-foreach(i=1:dim(m)[2]) %do% {names(which(m[,i]>0))}
names(m)<-paste("Cluster",c("X0","X1","X2","X3","X4","X5","X6","X7"),sep=" ")
y<-fromList(m)
upset(y,nsets=8,nintersects = NA,
      matrix.dot.alpha=0.5,order.by="freq")
#####enrichment analysis and making supplemental table 3
###get databases
msigdb_info <- hypeR::download_msigdb(species="Homo sapiens") 
BIOCARTA <- db_get(msigdb_info, "C2.CP.BIOCARTA")
KEGG     <- db_get(msigdb_info, "C2.CP.KEGG")
REACTOME <- db_get(msigdb_info, "C2.CP.REACTOME")
paths<-c(BIOCARTA, KEGG, REACTOME)
GOBP <- db_get(msigdb_info, "C5.BP")
GOMF <- db_get(msigdb_info, "C5.MF")
GOCC <- db_get(msigdb_info, "C5.CC")

cluster.genes.10x<-foreach(i=0:max(as.numeric(levels(obj@active.ident)))) %do% {
  x<-markers.10x[markers.10x$cluster==i,]
  rownames(x[x$p_val_adj<0.1,])
}
names(cluster.genes.10x)<-paste("Cluster",0:7,sep="_")
foreach(i=1:length(cluster.genes.10x),.combine='c') %do% {
  length(cluster.genes.10x[[i]])}


cluster.enr.10x<-foreach(i=1:length(cluster.genes.10x)) %do% {
  
  PATHWAYS<-hypeR(cluster.genes.10x[[i]], paths, bg=23459, fdr=0.01)[,1:7]
  GOBioProc<-hypeR(cluster.genes.10x[[i]], GOBP, bg=23459, fdr=0.01)[,1:7]
  GOMoleFunc<-hypeR(cluster.genes.10x[[i]], GOMF, bg=23459, fdr=0.01)[,1:7]
  GOCellComp<-hypeR(cluster.genes.10x[[i]], GOCC, bg=23459, fdr=0.01)[,1:7]
  list(PATHWAYS,GOBioProc,GOMoleFunc,GOCellComp)
}
names(cluster.enr.10x)<-paste("Cluster",sapply(0:7, function(z) paste("x",z,sep="")),sep="_")

enr<-c("Pathways","GO:BP","GO:MF","GO:CC")

x<-foreach(i=1:length(cluster.enr.10x), .combine='rbind') %do% {
  y<-cluster.enr.10x[[i]]
  z<-foreach(b=1:4, .combine='rbind') %do% {
    m<-y[[b]]
    if(dim(m)[1]==0) {} else {m$Type<-enr[b]}
    m
  }
  if(dim(z)[1]==0) {} else {z$Cluster<-names(cluster.enr.10x)[i]}
  z
}

write.csv(x,"Supplemental_Table_3.csv",row.names=F)


#####making a word cloud based on the top words from all categoies in enrichment analysis for figure 1
### and getting rid of labels and common words
y<-c("Pathways","GOBP","GOMF","GOCC")


enr.df<-foreach(j=1:length(y),.combine='rbind') %do% {
  
  fin<-foreach(i=1:length(cluster.enr.10x),.combine='rbind') %do% {
    x<-cluster.enr.10x[[i]]
    if(dim(x[[j]])[1]==0){} else {
      x<-data.frame(x[[j]],rep(y[j],dim(x[[j]])[1]),rep(i-1,dim(x[[j]])[1]),rownames(x[[j]]))
    }
    
  }
  colnames(fin)<-c(colnames(cluster.enr.10x[[1]][[j]]),"Category","Cluster","Name")
  fin
}

words<-function(df1,freq,col_pal){
  x<-df1$category
  x<-unlist(strsplit(x,"_"))
  x<-data.frame(table(x))
  x<-x[order(x$Freq,decreasing=T),]
  x<-x[!(x$x=="REACTOME"),]
  x<-x[!(x$x=="BIOCARTA"),]
  x<-x[!(x$x=="PATHWAY"),]
  x<-x[!(x$x=="OF"),]
  x<-x[!(x$x=="AND"),]
  x<-x[!(x$x=="KEGG"),]
  x<-x[!(x$x=="BY"),]
  x<-x[!(x$x=="THE"),]
  x<-x[!(x$x=="GO"),]
  x<-x[!(x$x=="TO"),]
  x<-x[!(x$x=="PROCESS"),]
  x<-x[!(x$x=="CELL"),]
  x<-x[!(x$x=="REGULATION"),]
  colnames(x)<-c("word","freq")
  wordcloud(x$word,x$freq,min.freq=freq,random.order=F,random.color=F,max.words=200,
            colors=brewer.pal(8,col_pal))
}


x<-enr.df[(enr.df$Category=="GOBP"),]
words(x,5,"PRGn")


#sessionInfo()
#R version 4.0.2 (2020-06-22)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows >= 8 x64 (build 9200)

#Matrix products: default

#locale:
#[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
#[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

#attached base packages:
#[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

#other attached packages:
#[1] wordcloud_2.6        RColorBrewer_1.1-2   Seurat_3.2.0         ggplot2_3.3.2        pCalibrate_0.2-1    
#[6] MCMCpack_1.4-8       MASS_7.3-51.6        coda_0.19-3          exact2x2_1.6.5       exactci_1.3-3       
#[11] ssanv_1.1            org.Hs.eg.db_3.11.4  AnnotationDbi_1.50.3 IRanges_2.22.2       S4Vectors_0.26.1    
#[16] Biobase_2.48.0       BiocGenerics_0.34.0  doParallel_1.0.15    iterators_1.0.12     foreach_1.5.0       
#[21] hypeR_1.4.0         

#loaded via a namespace (and not attached):
 # [1] plyr_1.8.6            igraph_1.2.5          lazyeval_0.2.2        splines_4.0.2         listenv_0.8.0        
 # [6] digest_0.6.25         htmltools_0.5.0       magrittr_1.5          memoise_1.1.0         tensor_1.5           
 #[11] cluster_2.1.0         ROCR_1.0-11           openxlsx_4.1.5        globals_0.12.5        readr_1.3.1          
 #[16] matrixStats_0.56.0    colorspace_1.4-1      blob_1.2.1            rvest_0.3.6           rappdirs_0.3.1       
 #[21] ggrepel_0.8.2         xfun_0.16             dplyr_1.0.1           crayon_1.3.4          jsonlite_1.7.0       
 #[26] spatstat.data_1.4-3   spatstat_1.64-1       survival_3.1-12       zoo_1.8-8             ape_5.4              
 #[31] glue_1.4.1            kableExtra_1.1.0      polyclip_1.10-0       gtable_0.3.0          webshot_0.5.2        
 #[36] MatrixModels_0.4-1    leiden_0.3.3          future.apply_1.6.0    abind_1.4-5           SparseM_1.78         
 #[41] scales_1.1.1          msigdbr_7.1.1         DBI_1.1.0             miniUI_0.1.1.1        Rcpp_1.0.5           
 #[46] viridisLite_0.3.0     xtable_1.8-4          reticulate_1.16       bit_4.0.3             rsvd_1.0.3           
 #[51] htmlwidgets_1.5.1     httr_1.4.2            ellipsis_0.3.1        ica_1.0-2             pkgconfig_2.0.3      
 #[56] farver_2.0.3          uwot_0.1.8            deldir_0.1-28         tidyselect_1.1.0      rlang_0.4.7          
 #[61] reshape2_1.4.4        later_1.1.0.1         munsell_0.5.0         tools_4.0.2           visNetwork_2.0.9     
 #[66] generics_0.0.2        RSQLite_2.2.0         ggridges_0.5.2        evaluate_0.14         stringr_1.4.0        
 #[71] fastmap_1.0.1         goftest_1.2-2         yaml_2.2.1            mcmc_0.9-7            knitr_1.29           
 #[76] bit64_4.0.2           fitdistrplus_1.1-1    zip_2.0.4             purrr_0.3.4           RANN_2.6.1           
 #[81] pbapply_1.4-2         future_1.18.0         nlme_3.1-148          reactable_0.2.0       mime_0.9             
 #[86] quantreg_5.61         xml2_1.3.2            compiler_4.0.2        rstudioapi_0.11       plotly_4.9.2.1       
 #[91] png_0.1-7             spatstat.utils_1.17-0 tibble_3.0.3          tweenr_1.0.1          stringi_1.4.6        
 #[96] lattice_0.20-41       Matrix_1.2-18         vctrs_0.3.2           pillar_1.4.6          lifecycle_0.2.0      
#[101] lmtest_0.9-37         RcppAnnoy_0.0.16      data.table_1.13.0     cowplot_1.0.0         irlba_2.3.3          
#[106] conquer_1.0.1         httpuv_1.5.4          patchwork_1.0.1       R6_2.4.1              promises_1.1.1       
#[111] KernSmooth_2.23-17    gridExtra_2.3         codetools_0.2-16      withr_2.2.0           sctransform_0.2.1    
#[116] mgcv_1.8-31           hms_0.5.3             rpart_4.1-15          grid_4.0.2            tidyr_1.1.1          
#[121] rmarkdown_2.3         Rtsne_0.15            ggforce_0.3.2         shiny_1.5.0  









