#######analyze data generated by 10x genomics platform

library(hypeR)
library(doParallel)
library(org.Hs.eg.db)
library(pCalibrate)
library(ggplot2)
library(Seurat)
library(RColorBrewer)

#####function to generate a useful data.frame from a seurat object
probs<-function(object) {
  require(foreach)
  require(Seurat)
  clusters<-object@meta.data$seurat_clusters
  rawdata<-object@assays$RNA@counts
  cluster.probs<-foreach(i=0:max(as.numeric(levels(clusters))),.combine='cbind') %dopar% {
    clust.mat<-rawdata[,clusters==i]
    apply(clust.mat,1,function(x) length(which(x>0))/length(x))
  }
  
  delta.probs<-foreach(i=1:dim(cluster.probs)[2],.combine='cbind') %do% {
    fin<-foreach(m=1:dim(cluster.probs)[2],.combine='cbind') %dopar% {
      cluster.probs[,i]-cluster.probs[,m]
    }
    fin<-apply(fin,1,sum)
    return(fin)
  }
  c.names<-paste("Cluster",as.numeric(levels(clusters)),sep="_")
  colnames(delta.probs)<-c.names
  colnames(cluster.probs)<-c.names
  fin<-list(cluster.probs,delta.probs)
  return(fin)
}


######load count data after processing and create a Seurat object
load("~/Desktop/R/10x/BOL14172_dge_raw.Rdata")
RPE10x <- CreateSeuratObject(counts = dge, project = "RPE10x", min.cells = 3, min.features = 200)

RPE10x <- PercentageFeatureSet(RPE10x, pattern = "^MT-", col.name = "percent.mt")
# run sctransform
RPE10x <- SCTransform(RPE10x, vars.to.regress = "percent.mt", verbose = FALSE)
RPE10x <- FindVariableFeatures(RPE10x, selection.method = "vst", nfeatures = 2000)
RPE10x <- RunPCA(RPE10x, features = VariableFeatures(RPE10x), verbose = FALSE)
RPE10x <- RunUMAP(RPE10x, dims = 1:50, verbose = FALSE)
RPE10x <- FindNeighbors(RPE10x, dims = 1:50, verbose = FALSE)
RPE10x <- FindClusters(RPE10x, resolution = 1, verbose = FALSE)
RPE10x@meta.data$patient<-"4"
markers.10x<-FindAllMarkers(RPE10x, min.pct = 0.25)

#### analyze and generate figure panels

obj<-RNA.10x
DimPlot(obj)
DotPlot(obj,features=rev(c("RPE65","BEST1","BMP4","VSX1","VSX2","RHO","SAG","PDE6A")),scale.min = 0)

####read in RPE signiture list from PMID:26517551
x<-read.csv("human_RPE_signature_genes_26517551.csv",as.is=T)
y<-intersect(rownames(obj@assays$SCT@scale.data),x[,1])
z<-setdiff(x[,1],y)
z<-heatmap(obj@assays$SCT@scale.data[y,])
DoHeatmap(obj,features=rev(y[z$rowInd]))+scale_fill_distiller(palette="RdYlBu")

####make an upset plot of interwsection between 10X cluster exression and the RPE signature genes
test<-probs(obj)
m<-test[[1]][which((apply(test[[1]][intersect(rownames(test[[1]]),x[,1]),7:8],1,max)>0)),]
m<-foreach(i=1:dim(m)[2]) %do% {names(which(m[,i]>0))}
names(m)<-paste("Cluster",c("X0","X1","X2","X3","X4","X5","X6","X7"),sep=" ")
y<-fromList(m)
upset(y,nsets=8,nintersects = NA,
      matrix.dot.alpha=0.5,order.by="freq")
#####enrichment analysis and making supplemental table 3
###get databases
msigdb_info <- hypeR::download_msigdb(species="Homo sapiens") 
BIOCARTA <- db_get(msigdb_info, "C2.CP.BIOCARTA")
KEGG     <- db_get(msigdb_info, "C2.CP.KEGG")
REACTOME <- db_get(msigdb_info, "C2.CP.REACTOME")
paths<-c(BIOCARTA, KEGG, REACTOME)
GOBP <- db_get(msigdb_info, "C5.BP")
GOMF <- db_get(msigdb_info, "C5.MF")
GOCC <- db_get(msigdb_info, "C5.CC")

cluster.genes.10x<-foreach(i=0:max(as.numeric(levels(obj@active.ident)))) %do% {
  x<-markers.10x[markers.10x$cluster==i,]
  rownames(x[x$p_val_adj<0.1,])
}
names(cluster.genes.10x)<-paste("Cluster",0:7,sep="_")
foreach(i=1:length(cluster.genes.10x),.combine='c') %do% {
  length(cluster.genes.10x[[i]])}


cluster.enr.10x<-foreach(i=1:length(cluster.genes.10x)) %do% {
  
  PATHWAYS<-hypeR(cluster.genes.10x[[i]], paths, bg=23459, fdr=0.01)[,1:7]
  GOBioProc<-hypeR(cluster.genes.10x[[i]], GOBP, bg=23459, fdr=0.01)[,1:7]
  GOMoleFunc<-hypeR(cluster.genes.10x[[i]], GOMF, bg=23459, fdr=0.01)[,1:7]
  GOCellComp<-hypeR(cluster.genes.10x[[i]], GOCC, bg=23459, fdr=0.01)[,1:7]
  list(PATHWAYS,GOBioProc,GOMoleFunc,GOCellComp)
}
names(cluster.enr.10x)<-paste("Cluster",sapply(0:7, function(z) paste("x",z,sep="")),sep="_")

enr<-c("Pathways","GO:BP","GO:MF","GO:CC")

x<-foreach(i=1:length(cluster.enr.10x), .combine='rbind') %do% {
  y<-cluster.enr.10x[[i]]
  z<-foreach(b=1:4, .combine='rbind') %do% {
    m<-y[[b]]
    if(dim(m)[1]==0) {} else {m$Type<-enr[b]}
    m
  }
  if(dim(z)[1]==0) {} else {z$Cluster<-names(cluster.enr.10x)[i]}
  z
}

write.csv(x,"Supplemental_Table_3.csv",row.names=F)


#####making a word cloud based on the top words from all categoies in enrichment analysis for figure 1
### and getting rid of labels and common words
y<-c("Pathways","GOBP","GOMF","GOCC")


enr.df<-foreach(j=1:length(y),.combine='rbind') %do% {
  
  fin<-foreach(i=1:length(cluster.enr.10x),.combine='rbind') %do% {
    x<-cluster.enr.10x[[i]]
    if(dim(x[[j]])[1]==0){} else {
      x<-data.frame(x[[j]],rep(y[j],dim(x[[j]])[1]),rep(i-1,dim(x[[j]])[1]),rownames(x[[j]]))
    }
    
  }
  colnames(fin)<-c(colnames(cluster.enr.10x[[1]][[j]]),"Category","Cluster","Name")
  fin
}

words<-function(df1,freq,col_pal){
  x<-df1$category
  x<-unlist(strsplit(x,"_"))
  x<-data.frame(table(x))
  x<-x[order(x$Freq,decreasing=T),]
  x<-x[!(x$x=="REACTOME"),]
  x<-x[!(x$x=="BIOCARTA"),]
  x<-x[!(x$x=="PATHWAY"),]
  x<-x[!(x$x=="OF"),]
  x<-x[!(x$x=="AND"),]
  x<-x[!(x$x=="KEGG"),]
  x<-x[!(x$x=="BY"),]
  x<-x[!(x$x=="THE"),]
  x<-x[!(x$x=="GO"),]
  x<-x[!(x$x=="TO"),]
  x<-x[!(x$x=="PROCESS"),]
  x<-x[!(x$x=="CELL"),]
  x<-x[!(x$x=="REGULATION"),]
  colnames(x)<-c("word","freq")
  wordcloud(x$word,x$freq,min.freq=freq,random.order=F,random.color=F,max.words=200,
            colors=brewer.pal(8,col_pal))
}


x<-enr.df[(enr.df$Category=="GOBP"),]
words(x,5,"PRGn")











